import SideBar from '@/components/SideBar'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head />
      <body>
        <div className="flex">
          {/* sidebar */}
          <div className="bg-[#2021231 max-w-xs h-screen overflow-y-auto md:min-w-[20rem]">
            <SideBar />
          </div>
          {/* clientProvider - Notification */}
          <div className="bg-[#343541] flex-1">{children}</div>
        </div>
        </body>
    </html>
  )
}
